@file:Suppress("unused", "unused", "unused")

package com.luczka.mycoffee.ui.theme

import androidx.compose.ui.graphics.Color

// TODO: Change colors
val PrimaryLight = Color(0xff9b442a)
val OnPrimaryLight = Color(0xffffffff)
val PrimaryContainerLight = Color(0xffffdbcb)
val OnPrimaryContainerLight = Color(0xff341100)
val SecondaryLight = Color(0xFF015DB1)
val OnSecondaryLight = Color(0xffffffff)
val SecondaryContainerLight = Color(0xffd7e3ff)
val OnSecondaryContainerLight = Color(0xff001b3f)
val TertiaryLight = Color(0xff984061)
val OnTertiaryLight = Color(0xffffffff)
val TertiaryContainerLight = Color(0xffffd9e2)
val OnTertiaryContainerLight = Color(0xff3e001d)
val ErrorLight = Color(0xffba1a1a)
val OnErrorLight = Color(0xffffffff)
val ErrorContainerLight = Color(0xffffdad6)
val OnErrorContainerLight = Color(0xff410002)
val BackgroundLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xff201a18)
val OutlineLight = Color(0xff85736c)
val SurfaceLight = Color(0xffFFFBFF)
val OnSurfaceLight = Color(0xff201a18)
val SurfaceVariantLight = Color(0xffe5e5e5)
val OnSurfaceVariantLight = Color(0xff484848)


val PrimaryDark = Color(0xffffb692)
val OnPrimaryDark = Color(0xff552000)
val PrimaryContainerDark = Color(0xff793100)
val OnPrimaryContainerDark = Color(0xffffdbcb)
val SecondaryDark = Color(0xffabc7ff)
val OnSecondaryDark = Color(0xff002f65)
val SecondaryContainerDark = Color(0xff00458f)
val OnSecondaryContainerDark = Color(0xffd7e3ff)
val TertiaryDark = Color(0xffffb1c8)
val OnTertiaryDark = Color(0xff5e1132)
val TertiaryContainerDark = Color(0xff7b2949)
val OnTertiaryContainerDark = Color(0xffffd9e2)
val ErrorDark = Color(0xffffb4ab)
val OnErrorDark = Color(0xff690005)
val ErrorContainerDark = Color(0xff93000a)
val OnErrorContainerDark = Color(0xffffdad6)
val BackgroundDark = Color(0xff121212)
val OnBackgroundDark = Color(0xffede0db)
val OutlineDark = Color(0xffa08d85)
val SurfaceDark = Color(0xff121212)
val OnSurfaceDark = Color(0xffdadada)
val SurfaceVariantDark = Color(0xff414141)
val OnSurfaceVariantDark = Color(0xffbfbfbf)