package com.coffee.mycoffeeassistant.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xff984716)
val SecondaryLight = Color(0xff1d5db1)
val TertiaryLight = Color(0xff984061)
val ErrorLight = Color(0xffba1a1a)
val BackgroundLight = Color(0xfffffbff)
val OutlineLight = Color(0xff85736c)
val OnPrimaryLight = Color(0xffffffff)
val OnSecondaryLight = Color(0xffffffff)
val OnTertiaryLight = Color(0xffffffff)
val OnErrorLight = Color(0xffffffff)
val OnBackgroundLight = Color(0xff201a18)
val PrimaryContainerLight = Color(0xffffdbcb)
val SecondaryContainerLight = Color(0xffd7e3ff)
val TertiaryContainerLight = Color(0xffffd9e2)
val ErrorContainerLight = Color(0xffffdad6)
val SurfaceLight = Color(0xffFFFBFF)
val SurfaceVariantLight = Color(0xfff4ded5)
val OnPrimaryContainerLight = Color(0xff341100)
val OnSecondaryContainerLight = Color(0xff001b3f)
val OnTertiaryContainerLight = Color(0xff3e001d)
val OnErrorContainerLight = Color(0xff410002)
val OnSurfaceLight = Color(0xff201a18)
val OnSurfaceVariantLight = Color(0xff52443d)

val PrimaryDark = Color(0xffffb692)
val SecondaryDark = Color(0xffabc7ff)
val TertiaryDark = Color(0xffffb1c8)
val ErrorDark = Color(0xffffb4ab)
val BackgroundDark = Color(0xff201a18)
val OutlineDark = Color(0xffa08d85)
val OnPrimaryDark = Color(0xff552000)
val OnSecondaryDark = Color(0xff002f65)
val OnTertiaryDark = Color(0xff5e1132)
val OnErrorDark = Color(0xff690005)
val OnBackgroundDark = Color(0xffede0db)
val PrimaryContainerDark = Color(0xff793100)
val SecondaryContainerDark = Color(0xff00458f)
val TertiaryContainerDark = Color(0xff7b2949)
val ErrorContainerDark = Color(0xff93000a)
val SurfaceDark = Color(0xff201a18)
val SurfaceVariantDark = Color(0xff52443d)
val OnPrimaryContainerDark = Color(0xffffdbcb)
val OnSecondaryContainerDark = Color(0xffd7e3ff)
val OnTertiaryContainerDark = Color(0xffffd9e2)
val OnErrorContainerDark = Color(0xffffdad6)
val OnSurfaceDark = Color(0xffede0db)
val OnSurfaceVariantDark = Color(0xffd7c2b9)